### PR TITLE
Merge without_OA into develop

### PR DESCRIPTION
**Pull request by boblinchuan**
Maintaining both `without_OA` and `develop` is a hassle, so they should be merged. I propose (1) merging these two branches and (2) closing the without_OA branch from pybag and using develop moving forward. I started with Pybag, and now I'm ready for BAG framework. 

This PR is contingent on [Pybag PR](https://github.com/ucb-art/pybag/pull/4)

BAG has seen many feature updates (~ 1+ years) to without_OA since the divergence, so I will not list them here.

Changes needed to merge the branches: 
0) Update pybag (pending PR)
1) Added `can_use_oa_view` to check for existing of OA libs.
2) Restored OAInterface and added checks to allow / disallow usage.
3) Added check in `util/cache.py` and `module.py` to separate the SKILL schematic export.
4) Merge conflict clean up (no real issue)

For verifying the code, I tested gen and meas cell using both OA and SKILL flows with both OA libs available and not available (only using OAInterface without OA libs should fail, and it fails gracefully with a RuntimeError).
 
PS: Having more detailed unit tests would add to the confidence of this merge, but (1) all of the features since the divergence are additive and (2) we wouldn't be able to test with vs without OA anyways.

### CODE REVIEW

**Comment by ayan-biswas** [comment]
Looks good at a glance.
Both gen_cell.sh and meas_cell.sh test BAG outputting OA / SKILL. I recommend a few more tests for verifying OA / SKILL input to BAG. A few example test cases are:
1. write_tech_info.sh
2. import_sch_cellview()
3. any cell with black box layout. This tests OA / SKILL input and output. E.g. resistor layouts in a certain PDK.

**Review by FeliciaG — APPROVED** [review]
Lgtm. If Ayan's suggested tests all pass seems good to merge.

**Comment by boblinchuan** [comment]
> Looks good at a glance. Both gen_cell.sh and meas_cell.sh test BAG outputting OA / SKILL. I recommend a few more tests for verifying OA / SKILL input to BAG. A few example test cases are:
> 
> 1. write_tech_info.sh
> 2. import_sch_cellview()
> 3. any cell with black box layout. This tests OA / SKILL input and output. E.g. resistor layouts in a certain PDK.

**Comment by boblinchuan** [comment]
(Closed by accident).

Ayan, good call on the other test cases. They themselves seem fine, but I did find a separate SKILL schematic issue. Will follow up after I debug...

**Comment by boblinchuan** [comment]
^Regarding my above issue, looks like my issues were previously addressed by Ayan. Switching to the correct branches of xbase and bag3_analog fixed them. So I will need to merge those as well...

For now, this PR is ready to merge. Unless @ayan-biswas has any further comments, I will merge this tonight after my [CI jobs](https://github.com/boblinchuan/bag/actions/runs/10067501008) finishes.

**Review by ayan-biswas — APPROVED** [review]
Just in case you haven't already done so, I recommend going through my slides in the BAG3 doc drive where I documented some of the weird hacks that were needed to make without_OA work, including some hacks in the other repos like xbase, etc. If all those cases are verified, then you can go ahead with the merge.

**Pull request merged**
